@startuml physicalview_n3
skinparam Linetype polyline

rectangle "Browser" as client1 {
    [Client] as client
}

rectangle "??" as webserver {
    [Web App] as webapp
}

rectangle "??" as localhost {
    rectangle "Backend Process" as backendbox {
        [Backend] as backend
        [Anime Facts Core] as afc
    }
    database "AnimeDB\n<<SQLite>>" as AnimeDB

    rectangle "Database keeper" as keeper {

        [Backup Script] as backup
        [Synchronizer] as sync
    }

    storage "Local Backups" as localbackups
}

cloud "Cloud Storage\n<<Google drive>>" as cloudstorage {
    storage "Remote Backups" as remotebackups
}

cloud "Jikan API\n<<REST>>" as jikanapi

rectangle "??" as server1 {
    database "Database\n<<MongoDB>>" as Database
}

webapp --> backend : HTTPS
backend -up-> Database : DB Driver
backend ..> afc : linked
afc --> AnimeDB : SQLite3 API
client --> webapp : HTTPS

backup --> AnimeDB : reads
sync --> AnimeDB : synchronizes
sync --> jikanapi : HTTPS (fetch)
backup --> localbackups : writes
Database -left-> remotebackups : writes

@enduml
