[Database]
import_script=./../sql/pm/physical_model_1.sql

[Import]
; image_type can be webp or jpg
image_type=webp

; we store a "quality score" for sorting purposes, so we have more "quality" anime at the top of the list. 
; this is calculated with the average rating on mal_ ideally it would disappear when we have a better way to sort anime, but for now it is what it is.
use_quality_filtering=true
; The number of tiers to use when defining the quality score. 5 means that anime will be sorted into 5 tiers
; e.g. 0-2 avgr anime will be in tier 1, 2-4 avgr in tier 2, etc. If use_quality_filtering is false, this setting is ignored.
quality_tiers=3

; list of x to ignore when importing anime
blacklisted_tags=["hentai"]
blacklisted_types=["Music","Unknown"]